version: "3.8"

services:
  vaultwarden:
    build: .
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.igoralves.dev.br"
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - vaultwarden_data:/data
    ports:
      - "8001:80"

volumes:
  vaultwarden_data: